/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Glass(props) {
    const { nodes, materials } = useGLTF('/glass1.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0, -0.002, 0]} rotation={[-Math.PI / 2, 0, 0.292]} scale={0.001}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['ht6-1-85-80ddd(1)(2024-07-02_01_29_04)001'].geometry}
                    material={materials['ht6-1-85-80ddd(1)(2024-07-02 01_29_04):color:128:128:128']}
                    scale={9.905}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/glass1.glb')